openapi: 3.2.0
info:
  title: Device Location retrieval API
  description: This API provides the ability to retrieve a device location.
  version: wip
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-camara-commonalities: tbd
servers:
- url: '{apiRoot}/location-retrieval/vwip'
  variables:
    apiRoot:
      default: http://localhost:9091
      description: API root
tags:
- name: Location Retrieval
  description: Retrieve the location of a device
paths:
  /retrieve:
    post:
      tags:
      - Location Retrieval
      summary: Execute location retrieval for a user device
      description: Retrieve the area where a certain user device is localized.
      operationId: retrieveLocation
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetrievalLocationRequest'
            examples:
              INPUT_PHONE_NUMBER_MAX_AGE:
                summary: Phone number and maxAge
                description: Retrieve location for a device identified by a phone number, providing a maxAge
                value:
                  device:
                    phoneNumber: '+123456789'
                  maxAge: 120
              INPUT_PHONE_NUMBER_MAX_AGE_AND_SURFACE:
                summary: Phone number, maxAge and maxSurface
                description: Retrieve location for a device identified by a phone number, providing a maxAge and maxSurface
                value:
                  device:
                    phoneNumber: '+123456789'
                  maxAge: 120
                  maxSurface: 1000000
              INPUT_IP_ADDRESS_V4:
                summary: IPv4 address without maxAge
                description: Retrieve location for a device identified by an IPv4 address, without an indication for maxAge
                value:
                  device:
                    ipv4Address:
                      publicAddress: 123.234.1.2
                      publicPort: 1234
              INPUT_NO_DEVICE_AND_MAX_AGE:
                summary: Device not provided, only maxAge
                description: The device has to be deducted from token
                value:
                  maxAge: 120
              INPUT_PHONE_NUMBER_IP_ADDRESS_V4:
                summary: Both phone number and IPv4 address, without maxAge
                description: Retrieve location for a device identified both by a phone number and an IPv4 address, without an indication for maxAge
                value:
                  device:
                    phoneNumber: '+123456789'
                    ipv4Address:
                      publicAddress: 123.234.1.2
                      publicPort: 1234
      responses:
        '200':
          description: Location retrieval result
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
              examples:
                LOCATION_CIRCLE:
                  $ref: '#/components/examples/RETRIEVAL_CIRCLE'
                LOCATION_POLYGON:
                  $ref: '#/components/examples/RETRIEVAL_POLYGON'
                LOCATION_CIRCLE_WITH_DEVICE:
                  $ref: '#/components/examples/LOCATION_CIRCLE_WITH_DEVICE'
        '400':
          $ref: '#/components/responses/Generic400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
        '404':
          $ref: '#/components/responses/RetrieveLocationNotFound404'
        '422':
          $ref: '#/components/responses/RetrieveLocationUnprocessableEntity422'
      security:
      - openId:
        - location-retrieval:read
components:
  examples:
    RETRIEVAL_POLYGON:
      summary: polygon-based device location retrieval
      description: The device is localized within a polygon delimited by the provided coordinates.
      value:
        lastLocationTime: '2023-10-17T13:18:23.682Z'
        area:
          areaType: POLYGON
          boundary:
          - latitude: 45.754114
            longitude: 4.860374
          - latitude: 45.753845
            longitude: 4.863185
          - latitude: 45.75249
            longitude: 4.861876
          - latitude: 45.751224
            longitude: 4.861125
          - latitude: 45.751442
            longitude: 4.859827
    RETRIEVAL_CIRCLE:
      summary: circle-based device location retrieval
      description: The device is localized within a circle with a center at the specified coordinates and a radius of 800 meters.
      value:
        lastLocationTime: '2023-10-17T13:18:23.682Z'
        area:
          areaType: CIRCLE
          center:
            latitude: 45.754114
            longitude: 4.860374
          radius: 800
    LOCATION_CIRCLE_WITH_DEVICE:
      summary: circle-based device location retrieval, returning the device identifier used by the implementation
      description: The device is localized within a circle with a center at the specified coordinates and a radius of 800 meters. Response when the request used a 2-legged access token with multiple device identifiers, or possibly only a single device identifier.
      value:
        lastLocationTime: '2023-10-17T13:18:23.682Z'
        area:
          areaType: CIRCLE
          center:
            latitude: 45.754114
            longitude: 4.860374
          radius: 800
        device:
          phoneNumber: '+123456789'
  responses:
    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 403
                code:
                  enum:
                  - PERMISSION_DENIED
          examples:
            GENERIC_403_PERMISSION_DENIED:
              summary: Permission denied
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
    RetrieveLocationNotFound404:
      description: Not found
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 404
                code:
                  enum:
                  - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_IDENTIFIER_NOT_FOUND:
              summary: Identifier not found
              description: Some identifier cannot be matched to a device
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: Device identifier not found.
    Generic400:
      description: Bad Request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              summary: Invalid argument
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
    Generic401:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 401
                code:
                  enum:
                  - UNAUTHENTICATED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated and a new authentication is required
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials. A new authentication is required.
    RetrieveLocationUnprocessableEntity422:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 422
                code:
                  enum:
                  - SERVICE_NOT_APPLICABLE
                  - MISSING_IDENTIFIER
                  - UNSUPPORTED_IDENTIFIER
                  - UNNECESSARY_IDENTIFIER
                  - LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_AGE
                  - LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE
                  - LOCATION_RETRIEVAL.UNABLE_TO_LOCATE
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              summary: Service not applicable
              description: Service not applicable for the provided identifier
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not available for the provided identifier.
            GENERIC_422_MISSING_IDENTIFIER:
              summary: Missing identifier
              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: The device cannot be identified.
            GENERIC_422_UNSUPPORTED_IDENTIFIER:
              summary: Unsupported identifier
              description: None of the provided identifiers is supported by the implementation
              value:
                status: 422
                code: UNSUPPORTED_IDENTIFIER
                message: The identifier provided is not supported.
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              summary: Unnecessary identifier
              description: An explicit identifier is provided when a device or phone number has already been identified from the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: The device is already identified by the access token.
            LOCATION_RETRIEVAL_422_UNABLE_TO_FULFILL_MAX_AGE:
              summary: Unable to fulfill maxAge
              description: The system is not able to provide the fresh location required by the client
              value:
                status: 422
                code: LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_AGE
                message: Unable to provide expected freshness for location
            LOCATION_RETRIEVAL_422_UNABLE_TO_FULFILL_MAX_SURFACE:
              summary: Unable to fulfill maxSurface
              description: The system is not able to provide accurate acceptable surface required by the client
              value:
                status: 422
                code: LOCATION_RETRIEVAL.UNABLE_TO_FULFILL_MAX_SURFACE
                message: Unable to provide accurate acceptable surface for location
            LOCATION_RETRIEVAL_422_UNABLE_TO_LOCATE:
              summary: Unable to locate device
              description: The network cannot locate the device
              value:
                status: 422
                code: LOCATION_RETRIEVAL.UNABLE_TO_LOCATE
                message: The network is unable to locate the device
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        $ref: '#/components/schemas/XCorrelator'
  schemas:
    PhoneNumber:
      description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
      type: string
      pattern: ^\+[1-9][0-9]{4,14}$
      example: '+123456789'
    DeviceIpv6Address:
      description: 'The device should be identified by the observed IPv6 address, or by any single IPv6 address from within the subnet allocated to the device (e.g. adding ::0 to the /64 prefix).

        '
      type: string
      format: ipv6
      example: 2001:db8:85a3:8d3:1319:8a2e:370:7344
    Area:
      description: Base schema for all areas
      type: object
      properties:
        areaType:
          $ref: '#/components/schemas/AreaType'
      required:
      - areaType
      discriminator:
        propertyName: areaType
        mapping:
          CIRCLE: '#/components/schemas/Circle'
          POLYGON: '#/components/schemas/Polygon'
    AreaType:
      type: string
      description: 'Type of this area.

        CIRCLE - The area is defined as a circle.

        POLYGON - The area is defined as a polygon.

        '
      enum:
      - CIRCLE
      - POLYGON
    Device:
      description: 'End-user device able to connect to a mobile network. Examples of devices include smartphones or IoT sensors/actuators.


        The developer can choose to provide the below specified device identifiers:


        * `ipv4Address`

        * `ipv6Address`

        * `phoneNumber`

        * `networkAccessIdentifier`

        NOTE1: the network operator might support only a subset of these options. The API invoker can provide multiple identifiers to be compatible across different network operators. In this case the identifiers MUST belong to the same device. Where more than one device identifier is provided, only one identifier will be selected by the implementation and this choice indicated to the API consumer in the response.

        NOTE2: as for this Commonalities release, we are enforcing that the networkAccessIdentifier is only part of the schema for future-proofing, and CAMARA does not currently allow its use. After the CAMARA meta-release work is concluded and the relevant issues are resolved, its use will need to be explicitly documented in the guidelines.

        '
      type: object
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        networkAccessIdentifier:
          $ref: '#/components/schemas/NetworkAccessIdentifier'
        ipv4Address:
          $ref: '#/components/schemas/DeviceIpv4Addr'
        ipv6Address:
          $ref: '#/components/schemas/DeviceIpv6Address'
      minProperties: 1
    ErrorInfo:
      description: Common schema for errors
      type: object
      required:
      - status
      - code
      - message
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: A human-readable code to describe the error
        message:
          type: string
          description: A human-readable description of what the event represents
    NetworkAccessIdentifier:
      description: A public identifier addressing a subscription in a mobile network. In 3GPP terminology, it corresponds to the GPSI formatted with the External Identifier ({Local Identifier}@{Domain Identifier}). Unlike the telephone number, the network access identifier is not subjected to portability ruling in force, and is individually managed by each operator.
      type: string
      example: 123456789@domain.com
    RetrievalLocationRequest:
      description: Request to retrieve the location of a device. Device is not required when using a 3-legged access token, following the rules in the description.
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
        maxAge:
          type: integer
          minimum: 0
          description: Maximum age of the location information which is accepted for the location retrieval (in seconds). Absence of maxAge means "any age" and maxAge=0 means a fresh calculation.
        maxSurface:
          type: integer
          minimum: 1
          description: Maximum surface in square meters which is accepted by the client for the location retrieval. Absence of maxSurface means "any surface size".
          example: 1000000
    SingleIpv4Addr:
      description: A single IPv4 address with no subnet mask
      type: string
      format: ipv4
      example: 84.125.93.10
    Location:
      type: object
      description: Device location
      required:
      - lastLocationTime
      - area
      properties:
        lastLocationTime:
          $ref: '#/components/schemas/LastLocationTime'
        area:
          $ref: '#/components/schemas/Area'
        device:
          $ref: '#/components/schemas/DeviceResponse'
    DeviceResponse:
      description: 'An identifier for the end-user equipment able to connect to the network that the response refers to. This parameter is only returned when the API consumer includes the `device` parameter in their request (i.e. they are using a two-legged access token), and is relevant when more than one device identifier is specified, as only one of those device identifiers is allowed in the response.

        If the API consumer provides more than one device identifier in their request, the API provider must return a single identifier which is the one they are using to fulfil the request, even if the identifiers do not match the same device. API provider does not perform any logic to validate/correlate that the indicated device identifiers match the same device. No error should be returned if the identifiers are otherwise valid to prevent API consumers correlating different identifiers with a given end user.

        '
      allOf:
      - $ref: '#/components/schemas/Device'
      - maxProperties: 1
    DeviceIpv4Addr:
      type: object
      description: 'The device should be identified by either the public (observed) IP address and port as seen by the application server, or the private (local) and any public (observed) IP addresses in use by the device (this information can be obtained by various means, for example from some DNS servers).


        If the allocated and observed IP addresses are the same (i.e. NAT is not in use) then  the same address should be specified for both publicAddress and privateAddress.


        If NAT64 is in use, the device should be identified by its publicAddress and publicPort, or separately by its allocated IPv6 address (field ipv6Address of the Device object)


        In all cases, publicAddress must be specified, along with at least one of either privateAddress or publicPort, dependent upon which is known. In general, mobile devices cannot be identified by their public IPv4 address alone.

        '
      properties:
        publicAddress:
          $ref: '#/components/schemas/SingleIpv4Addr'
        privateAddress:
          $ref: '#/components/schemas/SingleIpv4Addr'
        publicPort:
          $ref: '#/components/schemas/Port'
      anyOf:
      - required:
        - publicAddress
        - privateAddress
      - required:
        - publicAddress
        - publicPort
      example:
        publicAddress: 84.125.93.10
        publicPort: 59765
    Port:
      description: TCP or UDP port number
      type: integer
      minimum: 0
      maximum: 65535
    LastLocationTime:
      description: Last date and time when the device was localized. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
      format: date-time
      type: string
      example: '2023-09-07T10:40:52Z'
    XCorrelator:
      type: string
      pattern: ^[a-zA-Z0-9-_:;.\/<>{}]{0,256}$
      example: b4333c46-49c0-4f62-80d7-f0ef930f1c46
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        $ref: '#/components/schemas/XCorrelator'
  securitySchemes:
    openId:
      description: OpenID Connect authentication
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
externalDocs:
  description: Project documentation at Camara
  url: https://github.com/camaraproject/DeviceLocation
